version: "3.5"

services:
  postgres:
    container_name: "${STAGE}-${APP_NAME}-postgres"
    image: postgres:12.2
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ".env"
  hasura:
    container_name: "${STAGE}-${APP_NAME}-hasura"
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        hasura_graphql_migrations_dir: /hasura-migrations
        hasura_graphql_metadata_dir: /hasura-metadata
    image: graphql-engine-boilerplate
    ports:
      - "8085:8080"
    env_file:
      - ".env"
    restart: on-failure
    volumes:
      - ./migrations:/hasura-migrations
      - ./metadata:/hasura-metadata
    depends_on:
      - postgres
volumes:
  postgres_data:
